BUDGETS = [5,10,20] #millions of dollars

CHANCE = "CHANCE"
ATTACKER = "ATTACKER"
ROOT_ATTACKER = "ROOT_ATTACKER"
DEFENDER = "DEFENDER"
MARKET = "MARKET"
MS_IN_MINUTE = 60000
MINUTES_IN_TRADING_DAY = 390