BUDGETS = [5,10,20] #millions of dollars

CHANCE = "CHANCE"
BUDGETS = []
ATTACKER = 1
DEFENDER = -1
MARKET = 0
BUY="BUY"
SELL="SELL"
SIM_TRADE="SIM_TRADE"
MS_IN_MINUTE = 60000
MINUTES_IN_TRADING_DAY = 390
MAX_ORDERS_PER_ASSETS = 2